### ISSUE TITLE
Package.getStylesheetsPath is deprecated.

### ISSUE THREAD

**Issue by baelter** [extrabacon/atom-turbo-javascript#14] opened 2015-05-20 14:57 UTC
Store package style sheets in the `styles/` directory instead of `stylesheets/` in the `turbo-javascript` package
```
Package.getStylesheetsPath (/usr/share/atom/resources/app.asar/src/package.js:460:9)
Package.getStylesheetPaths (/usr/share/atom/resources/app.asar/src/package.js:471:32)
Package.loadStylesheets (/usr/share/atom/resources/app.asar/src/package.js:453:38)
<unknown> (/usr/share/atom/resources/app.asar/src/package.js:183:19)
Package.measure (/usr/share/atom/resources/app.asar/src/package.js:163:15)
Package.load (/usr/share/atom/resources/app.asar/src/package.js:177:12)
```

**Comment by andischerer** [comment] 2015-05-20 15:25
duplicate of #11

**Closed** 2015-05-21 00:02 UTC
